M48
; DRILL file {KiCad (6.0.10)} date Mon Mar  6 16:47:15 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-06T16:47:15+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.3169Y-4.9744
X1.8307Y-1.2992
X4.4488Y-1.2992
X4.9705Y-5.0
T0
M30
